name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce, minimal reproduction if possible
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Affected URL (if applicable)
      placeholder: https://slouchdetector.net
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, versions
      placeholder: macOS 14, Safari 17, Node 20
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant console output
      render: shell

